---
- name: Create users and add SSH keys
  hosts: all
  become: yes
  become_method: sudo
  vars_files:
    - users.yml

  tasks:
    - name: Check if users exist, create if they don't
      user:
        name: "{{ item.username }}"
        password: "{{ item.password }}"
        state: present
        shell: /bin/bash
      loop: "{{ users }}"

    - name: Ensure users' .ssh directory exists
      file:
        path: "/home/{{ item.username }}/.ssh"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0700'
      loop: "{{ users }}"

    - name: Add provided public keys to authorized_keys
      authorized_key:
        user: "{{ item.username }}"
        state: present
        key: "{{ item.public_key }}"
      loop: "{{ users }}"

    - name: Ensure users' home directory has correct permissions
      file:
        path: "/home/{{ item.username }}"
        state: directory
        owner: "{{ item.username }}"
        group: "{{ item.username }}"
        mode: '0755'
      loop: "{{ users }}"

    - name: Add users to appropriate groups
      user:
        name: "{{ item.username }}"
        groups: "{{ item.groups }}"
        append: yes
      loop: "{{ users }}"
